joint_names:
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
  - joint_7
maximum_velocities:
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
maximum_accelerations:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 10.0
  - 10.0
  - 10.0