# Change robot speed to 100% by default
# changes following this PR : https://github.com/ros-planning/moveit/pull/1890 
default_velocity_scaling_factor: 1
default_acceleration_scaling_factor: 1

# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  $(arg prefix)joint_1:
    has_velocity_limits: true
    max_velocity: 1.33
    has_acceleration_limits: true
    max_acceleration: 4.94
  $(arg prefix)joint_2:
    has_velocity_limits: true
    max_velocity: 1.33
    has_acceleration_limits: true
    max_acceleration: 4.94
  $(arg prefix)joint_3:
    has_velocity_limits: true
    max_velocity: 1.33
    has_acceleration_limits: true
    max_acceleration: 4.94
  $(arg prefix)joint_4:
    has_velocity_limits: true
    max_velocity: 1.33
    has_acceleration_limits: true
    max_acceleration: 4.94
  $(arg prefix)joint_5:
    has_velocity_limits: true
    max_velocity: 1.16
    has_acceleration_limits: true
    max_acceleration: 9.5
  $(arg prefix)joint_6:
    has_velocity_limits: true
    max_velocity: 1.16
    has_acceleration_limits: true
    max_acceleration: 9.5
  $(arg prefix)joint_7:
    has_velocity_limits: true
    max_velocity: 1.16
    has_acceleration_limits: true
    max_acceleration: 9.5
  $(arg prefix)left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  $(arg prefix)right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  $(arg prefix)finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  $(arg prefix)right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  $(arg prefix)left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  $(arg prefix)right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0